/*------------------------------------------------------------------------------------------
:*                         TECNOLOGICO NACIONAL DE MEXICO
:*                       INSTITUTO TECNOLOGICO DE LA LAGUNA
:*                     INGENIERIA EN SISTEMAS COMPUTACIONALES
:*                       TOPICOS AVANZADOS DE PROGRAMACION "B"
:*
:*                   SEMESTRE: AGO-DIC/2021    HORA: 17-18 HRS
:*
:*                 Aplicacion que muestra un formulario para conexion de base de datos
:*        
:*  Archivo     : ConexionDBFrame.java
:*  Autor       : Victor Manuel Torres Vega    17130071
:*  Fecha       : 17/nov/2021
:*  Compilador  : JDK 11 + Netbeans 
:*  Descripci�n : Esta clase genera la interfaz grafica, que muestra un estatus de la conexion
:*                de la base de datos.
:*  Ultima modif:
:*  Fecha       Modific�                              Motivo
:*========================================================================================== 
:*  17/nov/2021 17130071 Victor Manuel Torres Vega    Agregado de prológo.
:*
:*  10/dic/2021 17130071 Victor Manuel Torres Vega    Implementacion de metodo ejecutar();
                                                      Modificacion a su parametro defaultCloseOperation.
:*------------------------------------------------------------------------------------------*/
package mx.tecnm.tap.jdbc;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author luxxo
 */
public class ConexionDBFrame extends javax.swing.JFrame {

    private Frame frmPadre = null;
    
    public ConexionDBFrame() {
        initComponents();
        //Inicializar la lista de DBMS
        
        this.JComboDBMS.removeAllItems();
        this.JComboDBMS.addItem(ConexionDB.JAVADB);
        this.JComboDBMS.addItem(ConexionDB.ACCESS);
        this.JComboDBMS.addItem(ConexionDB.MYSQL);
        this.JComboDBMS.addItem(ConexionDB.ORACLEXE);
        this.JComboDBMS.addItem(ConexionDB.SQLSERVER);
        
    }

    //se declara el formulario como padre de las demas aplicaciones
    public ConexionDBFrame(Frame padre)
    {
        this();
        this.frmPadre = padre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JComboDBMS = new javax.swing.JComboBox<>();
        jTextServidor = new javax.swing.JTextField();
        jTextBaseDatos = new javax.swing.JTextField();
        jTextPuerto = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jPasswordContraseña = new javax.swing.JPasswordField();
        jButAceptar = new javax.swing.JButton();
        jButSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion de la conexion");

        jLabel1.setText("DBMS");

        jLabel2.setText("Servidor");

        jLabel3.setText("Base de datos");

        jLabel4.setText("Puerto");

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña:");

        JComboDBMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextServidor.setText("localhost");

        jTextBaseDatos.setText("TOPICOS");
        jTextBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBaseDatosActionPerformed(evt);
            }
        });

        jTextPuerto.setText("1527");

        jTextUsuario.setText("TOPICOS");
        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });

        jPasswordContraseña.setText("2021");

        jButAceptar.setText("Aceptar");
        jButAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAceptarActionPerformed(evt);
            }
        });

        jButSalir.setText("Salir");
        jButSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(JComboDBMS, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButAceptar)
                                    .addComponent(jTextBaseDatos)
                                    .addComponent(jTextUsuario)
                                    .addComponent(jPasswordContraseña))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButSalir))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JComboDBMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButSalir)
                    .addComponent(jButAceptar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//---------------------------------------------------------------------------------------
    private void jButSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButSalirActionPerformed
//---------------------------------------------------------------------------------------

//---------------------------------------------------------------------------------------
    private void jButAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAceptarActionPerformed

        //Hace la conexion por medio de la clase.
        ConexionDB.getInstancia().conectar( JComboDBMS.getSelectedItem( ) .toString      ( ) ,
                                           jTextServidor.getText                        ( ) , 
                                           jTextPuerto.getText                          ( ) , 
                                           jTextBaseDatos.getText                       ( ) , 
                                           jTextUsuario.getText                         ( ) , 
                                           new String( jPasswordContraseña.getPassword  ( ) ) );
        //ejemplo
        //ConexionDB.getInstancia().conectar(ConexionDB.JAVADB, "localhost", "1527", "TOPICOS", "TOPICOS", "2021");
        
        if( ConexionDB.getInstancia( ).conectado ( ) ){
            if( frmPadre != null )
            {
                frmPadre.setVisible ( true );
                dispose ( ) ;
                
            JOptionPane.showMessageDialog ( this, "Conexion establecida" );
            }
        }
        else
            JOptionPane.showMessageDialog ( this, "Conexion no establecida verifique informacion de conexion" );
    }//GEN-LAST:event_jButAceptarActionPerformed

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void jTextBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBaseDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBaseDatosActionPerformed
//---------------------------------------------------------------------------------------
    
//-------------------------------------------------------------------------------------------    
    public static void main(String args[]) {
        ejecutar();
    }
//-------------------------------------------------------------------------------------------    
    public static void ejecutar()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionDBFrame().setVisible(true);
            }
        });
    }
//-------------------------------------------------------------------------------------------    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboDBMS;
    private javax.swing.JButton jButAceptar;
    private javax.swing.JButton jButSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordContraseña;
    private javax.swing.JTextField jTextBaseDatos;
    private javax.swing.JTextField jTextPuerto;
    private javax.swing.JTextField jTextServidor;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
