/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package app.pvgps.inventario;

import app.pvgps.modelo.ModuloProductos;
import app.pvgps.principal.JFramePrincipal;
import static app.pvgps.principal.JFramePrincipal.PRODUCTOS_POR_COD_BARRAS;
import static app.pvgps.principal.JFramePrincipal.TIT_MOD_PROD;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.Properties;
import java.util.Vector;
import javax.swing.JOptionPane;
import mx.tecnm.tap.jdbc.EjecutorSQL;

/**
 *
 * @author luxxo
 */
public class ModuloModificarEliminar extends javax.swing.JDialog {

    /**
     * Creates new form ModuloModificarEliminar
     */
    private  JFramePrincipal    frmPrincipal;
     private ModuloProductos    modelo;
     private String             accion;
     private Vector<String>     vecTiposColumnas;
     private String             sql;
     private Properties         propConsultasSQL;
    
    public ModuloModificarEliminar(java.awt.Frame parent, boolean modal) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextCodBarras = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButEliminar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();

        jLabel1.setText("Codigo de barras");

        jTextCodBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodBarrasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Console", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ELIMINAR PRODUCTO");

        jButEliminar.setText("Eliminar");
        jButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButEliminar)
                                        .addGap(84, 84, 84)
                                        .addComponent(jButCancelar))
                                    .addComponent(jTextCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(164, 164, 164))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButEliminar)
                    .addComponent(jButCancelar))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCodBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodBarrasActionPerformed
        // TODO add your handling code here:
        jButEliminar.doClick();
    }//GEN-LAST:event_jTextCodBarrasActionPerformed

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButCancelarActionPerformed

    private void jButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarActionPerformed
        // TODO add your handling code here:
        
        int confirma = JOptionPane.showConfirmDialog( this, "Eliminar el registro seleccionado ?",
                                     "eliminar", 
                                     JOptionPane.YES_NO_OPTION, 
                                     JOptionPane.QUESTION_MESSAGE
        );
        
        if( confirma == JOptionPane.NO_OPTION )
            return;
        
//       String  valorLlavePrimaria   = jTextCodBarras.getText();
//       String  tipoLlavePrimaria    = vecTiposColumnas.elementAt ( 0 );
//        
        String valor = jTextCodBarras.getText();
        String sql = "DELETE FROM PRODUCTOS WHERE COD_BARRAS = '"+valor+"'";
       
//        Object [][] args = {{ tipoLlavePrimaria , valorLlavePrimaria }};
        
        try {
            int registros = EjecutorSQL.sqlEjecutar( sql, null );
            if ( registros == 1 )
            {
//                frmPrincipal.desplegarRegistros(sql, args);
//                frmPrincipal.getJButAgregarProducto().doClick();
                JOptionPane.showMessageDialog( this , "El registro ha sido eliminado ", "Eliminar",
                        JOptionPane.INFORMATION_MESSAGE );
            }else {
                JOptionPane.showMessageDialog(this, "No se encontró el producto", "Eliminar", 
                        JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        } catch (SQLIntegrityConstraintViolationException ex)
           {
                JOptionPane.showMessageDialog(this, "No se puede eliminar el registro actual "
                        + "porque tiene registros  asociados en otras tablas"
                        , "Error,",JOptionPane.ERROR_MESSAGE);
           }
            
        catch (SQLException ex) {
            JOptionPane.showMessageDialog( this, ex, "Error", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_jButEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloModificarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloModificarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloModificarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloModificarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuloModificarEliminar dialog = new ModuloModificarEliminar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextCodBarras;
    // End of variables declaration//GEN-END:variables
}
